# Shared configs
server: "mervine.net"
port: 80
uri: "/"
runs: 9

#httperf: # for 'render'
  # 'num-conns' is taken from 'runs' above and not supported here.
  # 'uri' is taken from 'uri' above and not supported here.
  #
  # Supports all other HTTPerf.rb configurations, see:
  #   http://mervine.net/gems/httperfrb

#yslow: # supported shown
  # ruleset: ydefault
  # ua: "<ua string>"
  # headers: '{ "foo": "bar" }'
  # viewport: "WxH"

phantomas: # for 'client'
  # 'runs' is taken from 'runs' above and not supported here.
  # 'url' is taken from 'uri' above and not supported here.
  #
  # Possible modules
  # ----------------
  #  Note: these are all on by default, so if you comment
  #  out the block, it's the same as leaving it on. I left
  #  them here for clarity of configuration.
  modules:
    - ajaxRequests
    - assetsTypes
    - cacheHits
    - caching
    - cookies
    - domComplexity
    - domQueries
    - domains
    - globalVariables
    - headers
    - localStorage
    - requestsStats
    - staticAssets
    - waterfall
    - windowPerformance

thresholds:

  render:
    # see HTTPerf.rb docs for all possible options:
    #   http://mervine.net/gems/httperfrb
    connection_time_median: 200 # ms
    #connection_time_avg:    400 # ms

    # The following require the modified version of httperf
    # from:
    #   http://github.com/rubyops/httperf
    #connection_time_85_pct: 200 # ms
    #connection_time_99_pct: 1500 # ms

  client:
    # Here's all of them, use as many or as few as you would like.
    #   Note: if you remove modules from 'phantomas' config above,
    #   some of these may become unavailable and autobench will
    #   error.
    requests: 145.0
    gzipRequests: 31.0
    postRequests: 0.0
    redirects: 3.0
    notFound: 0.0
    timeToFirstByte: 45.5
    timeToLastByte: 159.0
    bodySize: 1581198.5
    contentLength: 1859141.5
    ajaxRequests: 2.0
    htmlCount: 8.0
    htmlSize: 168758.5
    cssCount: 4.0
    cssSize: 155605.0
    jsCount: 99.0
    jsSize: 1072517.0
    imageCount: 21.0
    imageSize: 113304.0
    base64Count: 3.0
    base64Size: 4079.0
    otherCount: 13.0
    otherSize: 54381.0
    cacheHits: 1.0
    cacheMisses: 0.0
    cachingNotSpecified: 13.0
    cachingTooShort: 81.0
    cachingDisabled: 3.0
    headersCount: 1755.0
    headersSentCount: 442.0
    headersRecvCount: 1313.0
    headersSize: 63270.5
    headersSentSize: 20424.0
    headersRecvSize: 42847.5
    assetsNotGzipped: 84.0
    assetsWithQueryString: 86.0
    smallImages: 16.0
    httpTrafficCompleted: 1626.0
    domains: 21.0
    DOMqueries: 3.0
    DOMinserts: 892.0
    jQuerySelectors: 0.0
    jQueryOnDOMReadyFunctions: 0.0
    cookiesSent: 0.0
    cookiesRecv: 521.0
    domainsWithCookies: 4.0
    documentCookiesLength: 230.5
    documentCookiesCount: 5.0
    bodyHTMLSize: 75566.5
    commentsSize: 0.0
    hiddenContentSize: 0.0
    whiteSpacesSize: 3273.0
    DOMelementsCount: 1175.0
    DOMelementMaxDepth: 12.0
    iframesCount: 10.0
    nodesWithInlineCSS: 116.0
    imagesWithoutDimensions: 8.0
    globalVariables: 48.0
    localStorageEntries: 0.0
    smallestResponse: 22.0
    biggestResponse: 171492.0
    fastestResponse: 16.0
    slowestResponse: 666.0
    medianResponse: 130.0
    onDOMReadyTime: 121.5
    windowOnLoadTime: 795.0

  yslow:
    overall:  60
    loadtime: 4000
    requests: 135
    size:     1700000


################################################################################
# MISC CONFIGS -- Can mostly be ignored.
################################################################################

#paths:
  # SCRIPTS - path should be to container directory.
  #
  #yslow:     "/path/to/where/yslow/is"
  #phantomas: "/path/to/where/phantomas/is"

  # BINARIES - path should be to actual binary. (uses PATH by default)
  #
  #phantomjs: "/path/to/phantomjs"
  #node:      "/path/to/node"
  #httperf:   "/path/to/httperf"

# vim: ft=yaml:
