# sample config
server: "mervine.net"
port: 80
uri: "/"

render:
  num-conns: 9
  # supports all HTTPerf.rb configurations, see:
  #   http://mervine.net/gems/httperfrb

#yslow: # supported shown
  # ruleset: ydefault
  # ua: "<ua string>"
  # headers: '{ "foo": "bar" }' #
  # viewport: "WxH"

client:
  # used to generate loadreport's config.json
  # these are the default options included as part of
  # loadreport, see:
  #   https://github.com/wesleyhales/loadreport
  task: "performance"
  userAgent: "chrome"
  userAgentAliases:
    iphone:  "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_0 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8A293 Safari/6531.22.7"
    android: "Mozilla/5.0 (Linux; U; Android 2.2; en-us; Nexus One Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"
    chrome:  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.12 Safari/535.11"
  wait: 0
  cacheWait: 200
  consolePrefix: "#"
  verbose: false

thresholds:

  render:
    # see HTTPerf.rb docs for all possible options:
    #   http://mervine.net/gems/httperfrb
    connection_time_median: 200 # ms
    connection_time_avg:    250 # ms

    # The following require the modified version of httperf
    # from:
    #   http://github.com/rubyops/httperf
    connection_time_85_pct: 500 # ms
    connection_time_99_pct: 750 # ms

  #client:
    #<mesaurement>: 500 # ms

  yslow:
    overall:  60
    loadtime: 2500
    requests: 135
    size:     1650000


################################################################################
# MISC CONFIGS -- Can mostly be ignored.
################################################################################

# Path to yslow.js, incase you want to change the version.
yslow_js: "./lib/yslow.js"
# see: http://yslow.org/phantomjs/

loadreport_js: "./lib/loadreport.js"
# see: https://github.com/wesleyhales/loadreport

#phantomjs: "/path/to/phantomjs"
# by default uses PATH

#httperf: "/path/to/httperf"
# by default uses PATH

# vim: ft=yaml:
