# sample config
server: "mervine.net"
port: 80
uri: "/"

render:
  num-conns: 9
  # supports all HTTPerf.rb configurations, see:
  #   http://mervine.net/gems/httperfrb

thresholds:

  render:
    # see HTTPerf.rb docs for all possible options:
    #   http://mervine.net/gems/httperfrb
    connection_time_median: 200 # ms
    connection_time_avg:    250 # ms

    # The following require the modified version of httperf
    # from:
    #   http://github.com/rubyops/httperf
    connection_time_85_pct: 500 # ms
    connection_time_99_pct: 750 # ms

  #client:
    #<mesaurement>: 500 # ms

  #yslow:
    #overall: 90 # score

# vim: ft=yaml:
