# sample config
server: "mervine.net"
port: 80
uri: "/"

render:
  num-conns: 9
  # supports all HTTPerf.rb configurations, see:
  #   http://mervine.net/gems/httperfrb

#yslow: # supported shown
  # ruleset: ydefault
  # ua: "<ua string>"
  # headers: '{ "foo": "bar" }' #
  # viewport: "WxH"

thresholds:

  render:
    # see HTTPerf.rb docs for all possible options:
    #   http://mervine.net/gems/httperfrb
    connection_time_median: 200 # ms
    connection_time_avg:    250 # ms

    # The following require the modified version of httperf
    # from:
    #   http://github.com/rubyops/httperf
    connection_time_85_pct: 500 # ms
    connection_time_99_pct: 750 # ms

  #client:
    #<mesaurement>: 500 # ms

  yslow:
    overall:  60
    loadtime: 2500
    requests: 135
    size:     1650000


################################################################################
# MISC CONFIGS -- Can mostly be ignored.
################################################################################

# Path to yslow.js, incase you want to change the version.
yslow_js: "./lib/yslow.js"

#phantomjs: "/path/to/phantomjs"
# by default uses PATH

#httperf: "/path/to/httperf"
# by default uses PATH

# vim: ft=yaml:
